Merging r257833: ------------------------------------------------------------------------ r257833 | hans | 2016-01-14 15:18:20 -0800 (Thu, 14 Jan 2016) | 11 lines
Don't use __DATE__ or __TIME__; it breaks release builds (PR26145)

The release builds are configured to be reproducible, so that the
binaries compare equal between bootstrap iterations. The OpenMP
run-time build was failing like this:

runtime/src/kmp_version.c:108:79: error: expansion of date or time macro is not reproducible [-Werror,-Wdate-time]
char const __kmp_version_build_time[]     = KMP_VERSION_PREFIX "build time: " __DATE__ " " __TIME__;

Figuring as the build currently doesn't set LIBOMP_DATE, it's probably
OK to skip setting the build time here too.
------------------------------------------------------------------------


git-svn-id: https://llvm.org/svn/llvm-project/openmp/branches/release_38@257834 91177308-0d34-0410-b5e6-96231b3b80d8